version: '2.1'

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  monitor-net:
    driver: bridge

volumes:
    nginx_certs: {}
    nginx_vhost: {}
    nginx_html: {}
    nginx_acme: {}

services:

######################################################################################
#####################           POIFIER CONTAINER              #######################
######################################################################################

  poifier:
    image: grassets/poifier-client:v2.0.2
    container_name: poifier-testnet
    command:
      - '--poifier-server=https://goerli.poifier.io'
      - '--graph-node-status-endpoint=http://index-node-0:8030/graphql'
      - '--mnemonic=${OPERATOR_SEED_PHRASE}'
      - '--indexer-address=${STAKING_WALLET_ADDRESS}'
      - '--indexer-agent-epoch-subgraph-endpoint=${INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT:-https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle}'
    tty: true
    networks:
       - monitor-net
    restart: unless-stopped
    

######################################################################################
#####################            INDEXER AGENT GUI             #######################
######################################################################################

  indexer-agent-gui:
    image: ${INDEXER_AGENT_GUI:-ghcr.io/stakemachine/indexer-agent-ui:v0.1.9}
    container_name: indexer-agent-gui-testnet
    expose:
      - 3000
    environment:
      - UI_LOGIN=${ADMIN_USER:-test}
      - UI_PASS=${ADMIN_PASSWORD:-pass}
      - AGENT_ENDPOINT=${INDEXER_AGENT_ENDPOINT:-http://indexer-agent:8000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${AGENT_GUI_HOST}/
      - SUBGRAPH_ENDPOINT=${INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT:-https://gateway.testnet.thegraph.com/network}
      - VIRTUAL_HOST=${AGENT_GUI_HOST}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${AGENT_GUI_HOST}
    restart: unless-stopped
    networks:
      - monitor-net
      - net
    logging: *default-logging
